### ISSUE TITLE
小さな誤字

### ISSUE THREAD

**Issue by nihonbuson** [crab-ink/vol.4#17]
https://github.com/crab-ink/vol.4/blob/4d51cc1657b93ae403d0cd2167baadffedd9f1bd/yoshikiito.re#L1

> 採用時によくする６つの質問

→採用時によく聞く６つの質問

本文も「よく聞く」になっていたので、合わせるために、タイトルもこちらの方が良いかと。

https://github.com/crab-ink/vol.4/blob/4d51cc1657b93ae403d0cd2167baadffedd9f1bd/yoshikiito.re#L55

> バランスよく見についているか

→バランスよく身についているか

**Comment by YoshikiIto** [comment]
ありがとうございます！
3dbaa2c
にて対応しました！
